import Link from "next/link";
import { notFound } from "next/navigation";
import { StyleArchiveControl } from "@/app/components/styles/StyleArchiveControl";
import { Badge } from "@/app/components/ui/Badge";
import { Card } from "@/app/components/ui/Card";
import { PageHeader } from "@/app/components/ui/PageHeader";
import { getOwnedStyle } from "@/lib/styles/data";
import { getStyleStatusLabel, type StyleStatus } from "@/lib/styles/schema";
const variants: Record<StyleStatus, "success" | "neutral"> = { active: "success", archived: "neutral" };
const format = (value: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
function Item({ label, value }: { label: string; value: string | null }) { return <div className="min-w-0 rounded-control border border-border-soft bg-surface-soft p-4"><dt className="text-[0.6875rem] font-semibold uppercase tracking-[0.16em] text-text-muted">{label}</dt><dd className="mt-2 break-words text-sm leading-6 text-text-primary">{value || "Not added"}</dd></div>; }
export default async function StyleDetailPage({ params }: { params: Promise<{ styleId: string }> }) { const { styleId } = await params; const style = await getOwnedStyle(styleId); if (!style) notFound(); return <div><Link className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-text-secondary hover:text-accent-cyan" href="/fashion-studio/styles"><span aria-hidden="true">←</span>Style Library</Link><PageHeader action={<Link className="inline-flex min-h-12 items-center justify-center rounded-control border border-border-strong bg-surface-highlight px-5 py-3 text-sm font-semibold text-text-primary" href={`/fashion-studio/styles/${style.id}/edit`}>Edit style</Link>} description="Review the metadata for this reusable visual style." eyebrow="Style detail" title={style.name} /><div className="mt-6"><Badge variant={variants[style.status]}>{getStyleStatusLabel(style.status)}</Badge></div><Card className="mt-[var(--space-section)] p-5 sm:p-7"><dl className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Item label="Lighting" value={style.lighting} /><Item label="Camera" value={style.camera} /><Item label="Background" value={style.background} /><Item label="Mood" value={style.mood} /><Item label="Created" value={format(style.created_at)} /><Item label="Updated" value={format(style.updated_at)} /></dl></Card><section aria-label="Archive or restore style" className="mt-8 rounded-card border border-border-soft bg-surface-elevated p-5 shadow-card sm:p-6"><h2 className="text-base font-semibold text-text-primary">{style.status === "archived" ? "Restore style" : "Archive style"}</h2><div className="mt-3"><StyleArchiveControl status={style.status} styleId={style.id} /></div></section></div>; }
