import Link from "next/link";
import { AppIcon } from "@/app/components/ui/AppIcon";
import { Badge } from "@/app/components/ui/Badge";
import { Button } from "@/app/components/ui/Button";
import { Card } from "@/app/components/ui/Card";
import { EmptyState } from "@/app/components/ui/EmptyState";
import { Input } from "@/app/components/ui/Input";
import { PageHeader } from "@/app/components/ui/PageHeader";
import { getOwnedStyles } from "@/lib/styles/data";
import { getStyleStatusLabel, type StyleStatus } from "@/lib/styles/schema";

const variants: Record<StyleStatus, "success" | "neutral"> = { active: "success", archived: "neutral" };
function readValue(value: string | string[] | undefined) { return typeof value === "string" ? value : ""; }
function readStatus(value: string | string[] | undefined): "all" | "active" | "archived" { return value === "all" || value === "archived" || value === "active" ? value : "active"; }
function date(value: string) { return new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(value)); }

export default async function StyleLibraryPage({ searchParams }: { searchParams: Promise<{ q?: string | string[]; status?: string | string[] }> }) {
  const params = await searchParams; const search = readValue(params.q).trim().slice(0, 100); const status = readStatus(params.status); const styles = await getOwnedStyles({ search, status }); const hasFilters = Boolean(search) || status !== "active";
  return <div><Link className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-text-secondary transition hover:text-accent-cyan" href="/fashion-studio"><span aria-hidden="true">←</span>Fashion Studio</Link><PageHeader action={<Link className="inline-flex min-h-12 items-center justify-center rounded-control bg-gradient-to-r from-accent-cyan via-accent-blue to-accent-violet px-5 py-3 text-sm font-semibold text-white shadow-glow transition hover:brightness-110" href="/fashion-studio/styles/new">Add style <span aria-hidden="true">+</span></Link>} description="Store reusable visual styling metadata for consistent fashion content workflows." eyebrow="Fashion Studio" title="Style Library" />
    <Card className="mt-[var(--space-section)] p-4 sm:p-5"><form action="/fashion-studio/styles" className="grid gap-3 md:grid-cols-[minmax(0,1fr)_12rem_auto]" method="get"><div><label className="sr-only" htmlFor="style-search">Search styles</label><Input defaultValue={search} id="style-search" name="q" placeholder="Search name, lighting, camera, background, or mood" type="search" /></div><select className="min-h-12 rounded-control border border-border-soft bg-app/70 px-4 text-sm text-text-primary" defaultValue={status} name="status"><option value="all">All statuses</option><option value="active">Active</option><option value="archived">Archived</option></select><Button type="submit">Apply filters</Button></form>{hasFilters ? <div className="mt-3 flex justify-end"><Link className="text-sm font-medium text-text-secondary hover:text-accent-cyan" href="/fashion-studio/styles">Clear filters</Link></div> : null}</Card>
    <section aria-label="Styles" className="mt-6">{styles.length === 0 ? <Card><EmptyState action={<Link className="inline-flex min-h-10 items-center justify-center rounded-control border border-border-strong bg-surface-highlight px-4 py-2 text-sm font-semibold text-text-primary" href={hasFilters ? "/fashion-studio/styles" : "/fashion-studio/styles/new"}>{hasFilters ? "Clear filters" : "Create first style"}</Link>} description={hasFilters ? "No owned styles match the current search and status filter." : "Save reusable visual directions for lighting, camera, backgrounds, and mood."} icon={<AppIcon className="size-5" name="sparkles" />} title={hasFilters ? "No matching styles" : "Your Style Library is empty"} /></Card> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{styles.map((style) => <Card interactive key={style.id}><Link className="group flex min-h-56 flex-col p-5 sm:p-6" href={`/fashion-studio/styles/${style.id}`}><div className="flex items-start justify-between gap-4"><span className="grid size-11 place-items-center rounded-card border border-accent-violet/15 bg-gradient-to-br from-accent-violet/10 to-accent-cyan/10 text-accent-violet"><AppIcon className="size-5" name="sparkles" /></span><Badge variant={variants[style.status]}>{getStyleStatusLabel(style.status)}</Badge></div><div className="mt-5"><h2 className="break-words text-lg font-semibold text-text-primary">{style.name}</h2><p className="mt-1.5 line-clamp-2 text-sm text-text-secondary">{[style.lighting, style.camera, style.background, style.mood].filter(Boolean).join(" · ") || "Visual direction ready to complete"}</p></div><div className="mt-auto flex justify-between border-t border-border-soft pt-4"><div><p className="text-[0.6875rem] font-semibold uppercase tracking-[0.16em] text-text-muted">Updated</p><p className="mt-1 text-sm text-text-secondary">{date(style.updated_at)}</p></div><AppIcon className="size-4 text-text-muted group-hover:text-accent-cyan" name="arrow" /></div></Link></Card>)}</div>}</section></div>;
}
